
---
# This playbook deploys a PEBA instance and is proxy aware

- hosts: ews-test
  remote_user: root

  vars:
    proxy_env:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"

  roles:
    - peba

  environment: "{{proxy_env}}"

- hosts: ews-test-masternode
  remote_user: root

  vars:
    proxy_env:
        http_proxy: "{{ http_proxy }}"
        https_proxy: "{{ https_proxy }}"

  roles:
    - peba-masternode

  environment: "{{proxy_env}}"

